


conflict_prefer("filter", winner = "dplyr", quiet =  TRUE)
conflict_prefer("rename", winner = "dplyr", quiet =  TRUE)
conflict_prefer("select", winner = "dplyr", quiet =  TRUE)
conflict_prefer("slice", winner = "dplyr", quiet =  TRUE)
conflict_prefer("bart", winner = "parsnip", quiet =  TRUE)
conflict_prefer("fit", winner = "parsnip", quiet =  TRUE)
conflict_prefer("mars", winner = "parsnip", quiet =  TRUE)
conflict_prefer("pls", winner = "parsnip", quiet =  TRUE)
conflict_prefer("set_names", winner = "purrr", quiet =  TRUE)
conflict_prefer("cross", winner = "purrr", quiet =  TRUE)
conflict_prefer("invoke", winner = "purrr", quiet =  TRUE)
conflict_prefer("map", winner = "purrr", quiet =  TRUE)
conflict_prefer("discretize", winner = "recipes", quiet =  TRUE)
conflict_prefer("step", winner = "recipes", quiet =  TRUE)
conflict_prefer("populate", winner = "rsample", quiet =  TRUE)
conflict_prefer("rescale", winner = "scales", quiet =  TRUE)
conflict_prefer("expand", winner = "tidyr", quiet =  TRUE)
conflict_prefer("extract", winner = "tidyr", quiet =  TRUE)
conflict_prefer("pack", winner = "tidyr", quiet =  TRUE)
conflict_prefer("unpack", winner = "tidyr", quiet =  TRUE)
conflict_prefer("parameters", winner = "tune", quiet =  TRUE)
conflict_prefer("tune", winner = "tune", quiet =  TRUE)
conflict_prefer("get_weights", winner = "yardstick", quiet =  TRUE)
conflict_prefer("precision", winner = "yardstick", quiet =  TRUE)
conflict_prefer("recall", winner = "yardstick", quiet =  TRUE)
conflict_prefer("spec", winner = "yardstick", quiet =  TRUE)
conflict_prefer("update", winner = "recipes", loser = "Matrix", quiet = TRUE)
